### ISSUE TITLE
response to assigning new colour broken

### ISSUE THREAD

**Issue by Hyperfresh** [iwa/Q-Bot#35]
![image](https://user-images.githubusercontent.com/31476608/82001934-8abd9900-969b-11ea-8225-5877582ff2bc.png)

i also didn't notice it was happening to others too
![image](https://user-images.githubusercontent.com/31476608/82001959-a32db380-969b-11ea-92c3-60aaed621d74.png)
wonder what could be causing it...?

**Comment by Hyperfresh** [comment]
for reference: https://discordapp.com/channels/225359327525994497/611349541685559316/710626243103686737

**Comment by Hyperfresh** [comment]
i think it broke when i replaced \`\` with "" in color.ts as per 22d3eeb. problem with changing that is the "type `?color off`" won't work because of \`\`, so...

**Comment by Hyperfresh** [comment]
Found the solution! Probably. Doing \\\` might fix the issue. I'll send it over in a PR.

**Comment by Hyperfresh** [comment]
so commit cf65c2d / PR #37 should fix the issue. have a look

**Comment by iwa** [comment]
yeah, you have to use `` instead of ""
single and double quotes are used to register literal strings, and can only adds vars into them by using concatenation, which is a really bad thing for the memory

if i'm not wrong, `` comes from JQuery, and has been added to Node
do the same thing as `String.Format()` in C# and `.format()` in Python
